import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/Header/Header";
import { RevealObserver } from "@/components/atoms/RevealObserver/RevealObserver";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["cyrillic"]
})

export const metadata: Metadata = {
  title: "Стимул",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ru" className={`${rubik.variable}`}>
      <body>
        <Header />
        <RevealObserver />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
